### PR TITLE
RM-167437 Release w_common 2.1.1

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [FEA-1135: Implement `_ObservableTimer.tick`](https://github.com/Workiva/w_common/pull/168)

Requested by: @evanweible-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/2.1.0...Workiva:release_w_common_2.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/2.1.0...2.1.1

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6594079455444992/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6594079455444992/?repo_name=Workiva%2Fw_common&pull_number=169)

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by autobot-wk** [comment]
Skynet test results failed initially for this build but were approved by evan.weible
https://wf-skynet-hrd.appspot.com/apps/test/smithy/4156165/1
Approval message: Known failures on dev channel

**Review by evanweible-wf — APPROVED** [review]

**Comment by evanweible-wf** [comment]
QA +1
@Workiva/release-management-p

**Comment by evanweible-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
