### PR TITLE
RM-172950 Release w_common 2.1.2

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [Increase the minimum sass version](https://github.com/Workiva/w_common/pull/171)
	* [Update CI to 2.18](https://github.com/Workiva/w_common/pull/172)

Requested by: @robbecker-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/2.1.1...Workiva:release_w_common_2.1.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/2.1.1...2.1.2

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6594079455444992/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6594079455444992/?repo_name=Workiva%2Fw_common&pull_number=173)

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by robbecker-wf — APPROVED** [review]
+10

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
