### PR TITLE
WP-3710 Release w_common 1.4.0

### PR DESCRIPTION
**Pull request by rmconsole3-wf**
Pulls Included in Release:
* [RAP-1716 Add some additional management and helper methods](https://github.com/Workiva/w_common/pull/24)
* [RAP-1756 Remove Internal Disposable when Disposed Independently](https://github.com/Workiva/w_common/pull/25)

Requested by: @maxpeterson-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.3.0...version-bump-w_common-1-4-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.3.0...1.4.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by bencampbell-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
QA +1

- [x] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
