### PR TITLE
REF-1356 Add a dummy smithy file

### PR DESCRIPTION
**Pull request by georgelesica-wf**
> Please apply the appropriate label to your PR:
> - bug / critical
> - improvement / optimization / tech-debt / UX
> - feature

### Description

RM wants a Smithy file to do dependency scanning.

### Changes

Add the Smithy file they suggested.

### Semantic Versioning

> **This library is still pre-1.0.0.**
>
> Patches and minor changes will be released in a patch version, while breaking
> changes can be released in a minor version.

- [x] **Patch**
  - [x] This change does not affect the public API
  - [ ] This change fixes existing incorrect behavior without any additions
  - [ ] This change adds something to the public API
  - [ ] This change deprecates a part of the public API
- [ ] **Minor**
  - [ ] This change modifies part of the public API in a backwards-incompatible manner
  - [ ] This change removes part of the public API

### Testing/QA

- [ ] CI passes
- [ ] Approval from RM

### Code Review

@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf

@teresarevious-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by todbachman-wf** [comment]
+1

**Comment by travisreed-wf** [comment]
smithy will need to be turned on by the atlas team. Once that is done, you should be all set. +1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - adding smithy.yaml that will trigger future builds
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Pull request merged**
