### PR TITLE
WP-4904 Export DisposableManagerV6

### PR DESCRIPTION
**Pull request by evanweible-wf**
> Please apply the appropriate label to your PR:
> - bug / critical
> - improvement / optimization / tech-debt / UX
> - feature

### Description

`DisposableManagerV6` was added but not exported.

### Changes

Export `DisposableManagerV6`.

### Semantic Versioning

- [ ] **Patch**
  - [ ] This change does not affect the public API
  - [ ] This change fixes existing incorrect behavior without any additions
- [ ] **Minor**
  - [x] This change adds something to the public API
  - [ ] This change deprecates a part of the public API
* [ ] Major
  - [ ] This change modifies part of the public API in a backwards-incompatible manner
  - [ ] This change removes part of the public API

### Testing/QA

- [ ] CI passes

### Code Review

@dustinlessard-wf
@evanweible-wf
@jayudey-wf
@maxwellpeterson-wf
@sebastianmalysa-wf
@trentgrover-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by toddbeckman-wf** [comment]
+10

**Comment by georgelesica-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [ ] Tests created/updated 
  - no tests for library exports
- [x] All tests pass

@Workiva/release-management-pp

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [ ] Tests created/updated 
  - no tests for library exports
- [x] All tests pass

@Workiva/release-management-pp

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
