### PR TITLE
CP-3122 Release w_common 1.2.0

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [RAP-1500 Extract manage methods into an interface](https://github.com/Workiva/w_common/pull/17)

Requested by: @bencampbell-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.1.0...version-bump-w_common-1-2-0_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.1.0...1.2.0

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by georgelesica-wf** [comment]
+1

**Comment by ekweible** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by bencampbell-wf** [comment]
Quality Review Approval: +1

- [x] Dev +1's
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in

Merging into master.

**Pull request merged**
