### PR TITLE
WP-4908 Release w_common 1.8.1

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [RAP-2264 Allow managed timers to be canceled inside their callbacks](https://github.com/Workiva/w_common/pull/60)

Requested by: @georgelesica-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.8.0...version-bump-w_common-1-8-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.8.0...1.8.1

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by georgelesica-wf** [comment]
+1

**Comment by georgelesica-wf** [comment]
+1

**Comment by todbachman-wf** [comment]
+10. Confirmed Travis passed.

**Comment by todbachman-wf** [comment]
QA +1

- [x] Dev +1's
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in
- [x] Rosie reports a clean dependency scan

Merging into master
@Workiva/release-management-pp

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
