### PR TITLE
CP-2906 Release w_common 1.0.0

### PR DESCRIPTION
**Pull request by rmconsole2-wf**
Pulls Included in Release:
* [REF-1387 Implement manageDisposer()](https://github.com/Workiva/w_common/pull/9)

Requested by: @charliekump-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/0.2.0...version-bump-w_common-1-0-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/0.2.0...1.0.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinlessard-wf** [comment]
+1

**Comment by georgelesica-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
