### PR TITLE
RAP-2204 Cleanup.

### PR DESCRIPTION
**Pull request by aaronstgeorge-wf**
[Jira ticket](https://jira.atl.workiva.net/browse/RAP-2204)

### Description

The wording could be improved a little bit in tests.

### Changes

Clean up wording.

### Semantic Versioning

- [x] **Patch**
  - [x] This change does not affect the public API
  - [ ] This change fixes existing incorrect behavior without any additions
- [ ] **Minor**
  - [ ] This change adds something to the public API
  - [ ] This change deprecates a part of the public API
* [ ] Major
  - [ ] This change modifies part of the public API in a backwards-incompatible manner
  - [ ] This change removes part of the public API

### Testing/QA

- [ ] CI passes

### Code Review

@dustinlessard-wf
@evanweible-wf
@jayudey-wf
@maxwellpeterson-wf
@sebastianmalysa-wf
@trentgrover-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by bencampbell-wf** [comment]
+10

Things Tested
-------------
- [x] CI passes

**Comment by bencampbell-wf** [comment]
QA +1

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [ ] Security review (if required)
- [x] Unit tests created/updated 
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in
- [ ] Release Notes

Merging into master.
@Workiva/release-management-p

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
