### PR TITLE
Allow null args for the `manage___` APIs

### PR DESCRIPTION
**Pull request by patkujawa-wf**
## Motivation
I'm not sure how many unhandled exceptions have arisen from Disposable throwing exceptions, but calling `manageDisposable(null)` for sure throws (e.g. [OI-1470] SEV2-HI for Workiva folks).

I agree that consumers should check their inputs, but pragmatically, it's easy to mess that up and why should disposable care?

## Changes
Allow and ignore/return nulls for the manage-disposable APIs.

#### Release Notes
Allow and ignore/return nulls for the manage-disposable APIs.

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
        
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/w_common/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/w_common/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by patkujawa-wf** [comment]
<a href="https://github.com/Workiva/w_common/blob/master/CONTRIBUTING.md#coding-standards">Format your code using pub run dart_dev format (this is enforced by a CI check)
</a>

:sus:

**Comment by patkujawa-wf** [comment]
I would have thought that <a href="https://github.com/Workiva/w_common/blob/e42273a40b8a73fcba56b1ba91c8910397a910a0/test/unit/disposable_common.dart#L21-L23">testManageMethod</a> would end up with some failed tests but... nope? 😬

**Comment by patkujawa-wf** [comment]
I don't see Travis CI running at all any more 🤔

**Comment by patkujawa-wf** [comment]
Does Travis only run on non-draft PRs?

**Review by todbachman-wf — APPROVED** [review]
+1 to Pat's changes. 😄

**Review by robbecker-wf — APPROVED** [review]

**Review by evanweible-wf — APPROVED** [review]

**Comment by todbachman-wf** [comment]
@Workiva/release-management-pp

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Comment by patkujawa-wf** [comment]
Ugh
```
Because w_common >=1.20.7 depends on logging ^1.0.1 and wdesk_sdk depends on logging ^0.11.3+2, w_common >=1.20.7 is forbidden.
So, because wdesk_sdk depends on w_common ^1.20.9, version solving failed.
```

**Pull request merged**
