### PR TITLE
WP-5962 Fix outdated docs

### PR DESCRIPTION
**Pull request by georgelesica-wf**
> Please apply the appropriate label to your PR:
> - bug / critical
> - improvement / optimization / tech-debt / UX
> - feature

### Description

@regenvanwalbeek-wf pointed out that we had conflicting recommendations about how to use Disposable.

### Changes

Update the docs to consistently recommend the right patterns.

### Semantic Versioning

- [x] **Patch**
  - [ ] This change does not affect the public API
  - [ ] This change fixes existing incorrect behavior without any additions
- [ ] **Minor**
  - [ ] This change adds something to the public API
  - [ ] This change deprecates a part of the public API
* [ ] Major
  - [ ] This change modifies part of the public API in a backwards-incompatible manner
  - [ ] This change removes part of the public API

### Testing/QA

- [ ] CI passes

### Code Review

@dustinlessard-wf
@evanweible-wf
@jayudey-wf
@maxwellpeterson-wf
@sebastianmalysa-wf
@trentgrover-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

## Magpie
<details>
<summary>Number of findings: 0</summary>

</details>

**Comment by regenvanwalbeek-wf** [comment]
+1 Thank you!

**Comment by smaifullerton-wk** [comment]
+10 CI passes

**Comment by smaifullerton-wk** [comment]
QA +1
- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [ ] Security review (if required)
- [ ] Unit tests created/updated - N/A  documentation
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in

@Workiva/release-management-p

**Pull request merged**
