### PR TITLE
WP-4585 Add comment about deprecated entry point.

### PR DESCRIPTION
**Pull request by evanweible-wf**
### Description

Add a doc comment about the deprecated entry point.

### Changes

**Docs only change!**

### Semantic Versioning

- [x] **Patch**
  - [x] This change does not affect the public API
  - [ ] This change fixes existing incorrect behavior without any additions
- [ ] **Minor**
  - [ ] This change adds something to the public API
  - [ ] This change deprecates a part of the public API
* [ ] Major
  - [ ] This change modifies part of the public API in a backwards-incompatible manner
  - [ ] This change removes part of the public API

### Testing/QA

- [ ] CI passes

### Code Review

@Workiva/web-platform-pp @Workiva/rich-app-platform-pp

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by georgelesica-wf** [comment]
+1

**Comment by toddbeckman-wf** [comment]
+1

**Comment by georgelesica-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+10
- Docs only change

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [ ] Tests created/updated 
  - Docs/comment only.
- [x] All tests pass

@Workiva/release-management-pp

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
