### PR TITLE
RAP-1756 Remove Internal Disposable when Disposed Independently

### PR DESCRIPTION
**Pull request by bencampbell-wf**
### Description

If a disposable object  is managed but disposed independently of the parent disposable object, a reference to the child disposable is maintained until the parent is disposed. This allows a top level or long living disposable object to hold onto references to otherwise disposed instances longer than necessary.

### Changes

Watch the managed disposable didDispose events and remove them from the internal collection of things to dispose. This prevents the parent disposable object from maintaining a reference to child object.

### Semantic Versioning

- [x] **Patch**
  - [x] This change does not affect the public API
  - [x] This change fixes existing incorrect behavior without any additions
- [ ] **Minor**
  - [ ] This change adds something to the public API
  - [ ] This change deprecates a part of the public API
* [ ] Major
  - [ ] This change modifies part of the public API in a backwards-incompatible manner
  - [ ] This change removes part of the public API

### Testing/QA

- [ ] CI passes

### Code Review

@dustinlessard-wf
@evanweible-wf
@jayudey-wf
@maxwellpeterson-wf
@sebastianmalysa-wf
@trentgrover-wf
@georgelesica-wf 
@todbachman-wf 
@aaronstgeorge-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by bencampbell-wf** [comment]
I had to remove the changes to `manageStreamController` as the change only allows broadcast streams. If any consumers are passing in non broadcast streams the addition of the new listener throws an exception.

**Comment by bencampbell-wf** [comment]
This PR is dependent on https://github.com/Workiva/w_common/pull/26 in order to correct a bug in the CI run.

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for you

**Comment by georgelesica-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA +1

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
 - commented out code change and verified that test is now failing
- [ ] Security review (if required)
- [ ] Unit tests created/updated - N/A dep bump
- [ ] All unit tests pass
- [ ] Rosie has run and reports properly the release the ticket will be included in
- [ ] **Dependency Scan Clean**

Merging into master.

**Pull request merged**
