### PR TITLE
CP-2876 Release w_common 0.2.0

### PR DESCRIPTION
**Pull request by rmconsole2-wf**
Pulls Included in Release:
* [REF-1384 Cleanup and reorganization](https://github.com/Workiva/w_common/pull/5)

Requested by: @charliekump-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/0.1.0...version-bump-w_common-0-2-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/0.1.0...0.2.0

### CODE REVIEW

**Comment by ekweible** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by georgelesica-wf** [comment]
QA +1

- [x] Dev +1's
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in - PR title

Merging into master.

**Pull request merged**
