### PR TITLE
WP-3839 update runners, travis.yml

### PR DESCRIPTION
**Pull request by jayudey-wf**
@bencampbell-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by bencampbell-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+10
- CI passes

**Pull request merged**
