### PR TITLE
WP-3840 Release w_common 1.4.1

### PR DESCRIPTION
**Pull request by rm-astro-wf**
Pulls Included in Release:
* [RAP-1780 Handle single-subscription stream controllers better](https://github.com/Workiva/w_common/pull/28)

Requested by: @todbachman-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.4.0...version-bump-w_common-1-4-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.4.0...1.4.1

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by todbachman-wf** [comment]
+1

**Comment by georgelesica-wf** [comment]
+1

**Comment by todbachman-wf** [comment]
QA +1

- [x] Dev +1's
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in
- [x] Rosie reports a clean dependency scan

Merging into master

**Pull request merged**
