### PR TITLE
WP-3952 Release w_common 1.5.0

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [WP-4012 Add a docs.yml](https://github.com/Workiva/w_common/pull/30)
* [RAP-2040 Large number of managed disposables cause massive GC hit](https://github.com/Workiva/w_common/pull/32)
* [RAP-2050 Add dev tooling](https://github.com/Workiva/w_common/pull/33)
* [RAP-2067 Add event listener helpers to Disposable.](https://github.com/Workiva/w_common/pull/35)

Requested by: @todbachman-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.4.1...version-bump-w_common-1-5-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.4.1...1.5.0

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by bencampbell-wf** [comment]
+1

**Comment by smaifullerton-wk** [comment]
+1

**Comment by todbachman-wf** [comment]
QA +1

- [x] Dev +1's
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in
- [x] Rosie reports a clean dependency scan

Merging into master

**Pull request merged**
