### PR TITLE
WP-3218 Release w_common 1.3.0

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [RAP-1654 Add Managed Timer Factories](https://github.com/Workiva/w_common/pull/22)

Requested by: @bencampbell-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.2.0...version-bump-w_common-1-3-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.2.0...1.3.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by bencampbell-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by bencampbell-wf** [comment]
Quality Review Approval: +1

- [x] Dev +1's
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in

Merging into master.

**Comment by maxwellpeterson-wf** [comment]
+1

**Pull request merged**
