### PR TITLE
AF-297 Release w_common 1.13.0

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Requested by: @kerbyseeley-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.12.0...Workiva:release_w_common_1_13_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.12.0...1.13.0

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6594079455444992/logs/)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by seanstrickland-wf** [comment]
+1

**Comment by georgelesica-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
