### PR TITLE
CP-2939 Release w_common 1.1.0

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [CP-2947 Update smithy.yaml](https://github.com/Workiva/w_common/pull/11)
* [REF-1399 Fail immediately on null argument](https://github.com/Workiva/w_common/pull/14)
* [RAP-1455 Add isDisposing and isDisposedOrDisposing](https://github.com/Workiva/w_common/pull/15)

Requested by: @todbachman-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.0.0...version-bump-w_common-1-1-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.0.0...1.1.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by georgelesica-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by todbachman-wf** [comment]
QA +1

- [x] Dev +1's
- [x] All unit tests pass
- [ ] Rosie has run and reports properly the release the ticket will be included in
- [ ] Rosie reports a clean dependency scan

Merging into master.

**Comment by todbachman-wf** [comment]
@rmconsole-wf

**Pull request merged**
